Shopp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shoppapp.urls')),

    # DJANGO AUTHENTICATION URLS CONF
    path("account/", include("django.contrib.auth.urls")),
    # DJANGO FLUTTERWAVE URLS CONF
    path("djangoflutterwave/", include("djangoflutterwave.urls", namespace="djangoflutterwave"))

]

shoppapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import *


app_name = 'shoppapp'
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("products/", ProductsView.as_view(), name="products"),
    path("product/<int:pk>/<str:name>/details/", product_detail_view, name="product_details"),

    path("about/", AboutUsView.as_view(), name="about"),
    path("contact/", ContactUsView.as_view(), name="contact"),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shoppapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    """STORES PRODUCT DETAILS"""
    name = models.CharField(max_length=50)
    price = models.DecimalField(default=0.0, decimal_places=2, max_digits=100)
    discount_price = models.DecimalField(default=0.0, decimal_places=2, max_digits=100)
    product_image = models.ImageField(upload_to="Products/")
    description = models.TextField(max_length=500)
    featured_tag = models.BooleanField(default=True,
                                       help_text="Check this field if you want this product to be in the featured list"
                                       )
    date_added = models.DateTimeField(auto_now_add=True)
    added_to_cart = models.BooleanField(default=False)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return f"{self.name} ${self.price}"


class ProductOrder(models.Model):
    """STORES THE ORDERS ON RECORD"""
    user = models.ForeignKey(User, related_name="ordered_by", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name="product_order", on_delete=models.CASCADE)
    address = models.CharField(max_length=100, help_text="Address of delivery")
    state = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    order_date = models.DateTimeField(auto_now_add=True, help_text="Date the product is ordered")
    paid = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False, help_text="Marked when the product is delivered")
    pending = models.BooleanField(default=True, help_text="It's unmarked when the product is delvered")

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return f"{self.product} {self.product.price}"


class UserContact(models.Model):
    """STORES THE CONTACT DETAILS OF USER"""
    name = models.CharField(max_length=100),
    email = models.EmailField(max_length=125)
    subject = models.CharField(max_length=50)
    message = models.TextField(max_length=500)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name


class Subscriber(models.Model):
    """STORES THE DETAILS OF SUBSCRIBERS"""
    user_email = models.EmailField(max_length=125)

    def __str__(self):
        return self.user_email

shoppapp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import (
    ListView, TemplateView,
    DetailView,
)
from django.contrib.auth.views import (
    LoginView,
)

from .models import (
    Product
)


class HomeView(ListView):
    template_name = "shoppapp/index.html"
    model = Product
    context_object_name = "products"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        return context


class ProductsView(TemplateView):
    template_name = "shoppapp/products.html"
    pass


class AboutUsView(TemplateView):
    template_name = "shoppapp/about.html"
    pass


class ContactUsView(TemplateView):
    template_name = "shoppapp/contact.html"
    pass


def product_detail_view(request, pk, name):
    template = "shoppapp/product_details.html"
    product = get_object_or_404(Product, id=pk)
    products = Product.objects.all()
    context = {
        "product": product,
        "products": products,
        "name": name,
    }
    return render(request, template, context)

#
# def user_registration(request):
#     """HANDLES USER REGISTRATION"""
#     template

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Bags shopping payment order cart buying selling ordering reference">
    <meta name="author" content="Ikegbunam Udokike Daniel">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>{% block title %} Default Page Title {% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'shoppapp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'shoppapp/assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'shoppapp/assets/css/tooplate-main.css' %}">
    <link rel="stylesheet" href="{% static 'shoppapp/assets/css/owl.css' %}">
<!--
Tooplate 2114 Pixie
https://www.tooplate.com/view/2114-pixie
-->
  </head>

  <body>
    {% include "partials/_navs.html" %}
    {% block content %}
      <!-- DEFAULT BODY FOR ALL HTML THAT WILL INHERIT THE BASE HTML -->
    {% endblock content %}

    <!-- Subscribe Form Starts Here -->
    <div style="background: #800080" class="subscribe-form">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Subscribe on PIXIE now!</h1>
            </div>
          </div>
          <div class="col-md-8 offset-md-2">
            <div class="main-content">
              <p>Integer vel turpis ultricies, lacinia ligula id, lobortis augue. Vivamus porttitor dui id dictum efficitur. Phasellus vel interdum elit.</p>
              <div class="container">
                <form id="subscribe" action="" method="get">
                  <div class="row">
                    <div class="col-md-7">
                      <fieldset>
                        <input name="email" type="text" class="form-control" id="email" 
                        onfocus="if(this.value == 'Your Email...') { this.value = ''; }" 
                    	onBlur="if(this.value == '') { this.value = 'Your Email...';}"
                    	value="Your Email..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-5">
                      <fieldset>
                        <button type="submit" id="form-submit" class="button">Subscribe Now!</button>
                      </fieldset>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Subscribe Form Ends Here -->

    {% include "partials/_footer.html" %}
  

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'shoppapp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'shoppapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


    <!-- Additional Scripts -->
    <script src="{% static 'shoppapp/assets/js/custom.js' %}"></script>
    <script src="{% static 'shoppapp/assets/js/owl.js' %}"></script>


    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>


  </body>

</html>

templates/partials/_footer.html
   {% load static %}
   <!-- Footer Starts Here -->
    <div style="background: #800080" class="footer">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
            </div>
            <div class="col-md-12">
              <div class="copyright-text">
                <p style="color: #fff">Copyright &copy; 2019 Company Name 
                  
                  - Design: <a rel="nofollow" href="https://www.facebook.com/tooplate">Tooplate</a></p>
              </div>
            </div>
            <div class="col-md-12">
            </div>
          </div>
        </div>
      </div>
      <!-- Footer Ends Here -->

templates/partials/_navs.html
{% load static %}
<!-- Pre Header -->
<div style="background: #800080;" id="pre-header">
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <span>Suspendisse laoreet magna vel diam lobortis imperdiet</span>
        </div>
        <div class="col-md-6">
            <form style="margin-top: 10px;" action="#" method="post" role="form">
            {% csrf_token %}
            <div class="input-group">
              <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
                aria-describedby="search-addon" />
              <button type="button" class="btn btn-outline-primary">search</button>
            </div>
            </form>
          </div>
        <div class="col-md-4">
          <span>
            <i style="color:gold;padding: 20px;" class="fa fa-cog fa-2x"></i>
            <i style="color:gold;padding: 20px;" class="fa fa-user fa-2x"></i>
          </span>
        </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Navigation -->
  <div>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#"><i style="color:#800080; padding: 20px;" class="fa fa-shopping-cart fa-2x"></i></a>
      <button style="background: #800080;" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'shoppapp:home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shoppapp:products' %}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shoppapp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shoppapp:contact' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Signup</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

templates/shoppapp/about.html
{% extends "base.html" %}
{% load static %}

{% block title %} Shopp About Us {% endblock title %}

{% block content %}
    <!-- Page Content -->
    <!-- About Page Starts Here -->
    <div class="about-page">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div style="background: #800080;" class="line-dec"></div>
              <h1>About Us</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="left-image">
              <img src="{% static 'shoppapp/assets/images/about-us.jpg' %}" alt="">
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>Phasellus vel interdum elit</h4>
              <p><a href="https://www.pexels.com/photo/group-of-people-raising-right-hand-1059120/">Photo Credit</a> goes to Pexels website. Aliquam erat volutpat. Pellentesque fringilla, ligula consectetur cursus scelerisque, leo elit pellentesque sapien, et pharetra arcu elit vitae sem. Suspendisse erat dui, condimentum in mi ac, varius tempor sapien. Donec in justo sit amet ex aliquet maximus ac quis erat.</p> 
              <br>
              <p>Donec fermentum tincidunt tellus quis fermentum. Proin eget imperdiet purus. Nulla facilisi. Aliquam tincidunt porttitor dui sed euismod. Duis est libero, rhoncus fermentum turpis id, tempus fringilla ipsum. Nullam venenatis tincidunt neque vel hendrerit. Suspendisse porta pretium porttitor.</p>
              <br>
              <p>Sed purus quam, ultricies eu leo in, sollicitudin varius quam. Proin dictum urna ac diam fermentum tempus. Pellentesque urna urna, ullamcorper a tincidunt dignissim, venenatis in nisi. Vivamus in volutpat tellus. Etiam fermentum luctus posuere.</p>
              <br>
              <p><a rel="nofollow" href="https://www.tooplate.com/view/2114-pixie">Pixie HTML Template</a> can be converted into your desired CMS theme. You can use this Bootstrap v4.1.3 layout for any online shop. Please tell your friends about <a rel="nofollow" href="https://www.facebook.com/tooplate/">Tooplate</a>. Thank you.</p>
              <div class="share">
                <h6>Find us on: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Page Ends Here -->

{% endblock content %}

templates/shoppapp/contact.html
{% extends "base.html" %}
{% load static %}

{% block title %} Shopp Contact Us {% endblock title %}

{% block content %}
    <!-- Page Content -->
    <!-- About Page Starts Here -->
    <div class="contact-page">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div style="background: #800080;" class="line-dec"></div>
              <h1>Contact Us</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div id="map">
            		<!-- How to change your own map point
                           1. Go to Google Maps
                           2. Click on your location point
                           3. Click "Share" and choose "Embed map" tab
                           4. Copy only URL and paste it within the src="" field below
                    -->

              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1197183.8373802372!2d-1.9415093691103689!3d6.781986417238027!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfdb96f349e85efd%3A0xb8d1e0b88af1f0f5!2sKumasi+Central+Market!5e0!3m2!1sen!2sth!4v1532967884907" width="100%" height="500px" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <div class="container">
                <form id="contact" action="" method="post">
                  <div class="row">
                    <div class="col-md-6">
                      <fieldset>
                        <input name="name" type="text" class="form-control" id="name" placeholder="Your name..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-6">
                      <fieldset>
                        <input name="email" type="text" class="form-control" id="email" placeholder="Your email..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <input name="subject" type="text" class="form-control" id="subject" placeholder="Subject..." required="">
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your message..." required=""></textarea>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <button style="background: #800080;" type="submit" id="form-submit" class="button">Send Message</button>
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <div class="share">
                        <h6>You can also keep in touch on: <span><a href="#"><i style="background: #800080;" class="fa fa-facebook"></i></a><a href="#"><i style="background: #800080;" class="fa fa-linkedin"></i></a><a href="#"><i style="background: #800080;" class="fa fa-twitter"></i></a></span></h6>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- About Page Ends Here -->
    {% endblock content %}

templates/shoppapp/index.html
{% extends "base.html" %}
{% load static %}

{% block title %} Shopp Store {% endblock title %}

{% block content %}
  <!-- Page Content -->
  <!-- Banner Starts Here -->
  <div class="banner">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="caption">
            <h2>Ecommerce HTML Template</h2>
            <div style="background: #800080;" class="line-dec"></div>
            <p>Pixie HTML Template can be converted into your desired CMS theme. Total <strong>5 pages</strong> included. You can use this Bootstrap v4.1.3 layout for any CMS. 
            <br><br>Please tell your friends about <a rel="nofollow" href="https://www.facebook.com/tooplate/">Tooplate</a> free template site. Thank you. Photo credit goes to <a rel="nofollow" href="https://www.pexels.com">Pexels website</a>.</p>
            <div class="main-button">
              <a style="background: #800080;" href="#">Order Now!</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Banner Ends Here -->
   <!-- Featured Starts Here -->
   <div class="featured-items">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="section-heading">
            <div style="background: #800080;" class="line-dec"></div>
            <h1>Featured Items</h1>
          </div>
        </div>
        <div class="col-md-12">
          <div class="owl-carousel owl-theme">
            {% for product in products %}
              {% if product.featured_tag %}
              <a href="{% url 'shoppapp:product_details' product.id product.name %}">
                <div class="featured-item">
                  <img src="{{ product.product_image.url }}" alt="Item 1">
                  <h4>{{ product.name }}</h4>
                  <div style="display: flex;">
                    <h6 style="text-decoration: line-through; color: red;">NGN {{product.price}}</h6> 
                    <h6 style="margin-left: 10px;">NGN {{product.price}}</h6>
                  </div>
               </div>
              </a>
              {% else %}
              <!-- DO NOTHING -->
              {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Featred Ends Here -->

  <!-- Products display -->
  
  <div class="featured container no-gutter">
    <div class="row posts">
      {% for product in products  %}
        {% if not product.featured_tag %}
        <div id="1" class="item new col-md-4">
          <a href="{% url 'shoppapp:product_details' product.id product.name %}">
            <div class="featured-item">
              <img src="{{ product.product_image.url }}" alt="Item 1">
              <h4>{{ product.name }}</h4>
              <div style="display: flex;">
                <h6 style="text-decoration: line-through; color:red;">NGN {{product.price}}</h6> 
                <h6 style="margin-left: 10px;">NGN {{product.discount_price}}</h6>
              </div>
              <a style="background: #800080; color: #fff;" class="btn btn-block btn-primary" href="#">Order Now!</a>
            </div>
          </a>
        </div>
        {% endif %}
      {% endfor %}
    </div>
</div>
<!-- Products display ends -->

<!-- About Page Starts Here -->
<div class="about-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="section-heading">
          <div style="background: #800080;" class="line-dec"></div>
          <h1>About Us</h1>
        </div>
      </div>
      <div class="col-md-6">
        <div class="left-image">
          <img src="{% static 'shoppapp/assets/images/about-us.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-md-6">
        <div class="right-content">
          <h4>Phasellus vel interdum elit</h4>
          <p><a href="https://www.pexels.com/photo/group-of-people-raising-right-hand-1059120/">Photo Credit</a> goes to Pexels website. Aliquam erat volutpat. Pellentesque fringilla, ligula consectetur cursus scelerisque, leo elit pellentesque sapien, et pharetra arcu elit vitae sem. Suspendisse erat dui, condimentum in mi ac, varius tempor sapien. Donec in justo sit amet ex aliquet maximus ac quis erat.</p> 
          <br>
          <p>Donec fermentum tincidunt tellus quis fermentum. Proin eget imperdiet purus. Nulla facilisi. Aliquam tincidunt porttitor dui sed euismod. Duis est libero, rhoncus fermentum turpis id, tempus fringilla ipsum. Nullam venenatis tincidunt neque vel hendrerit. Suspendisse porta pretium porttitor.</p>
          <br>
          <p>Sed purus quam, ultricies eu leo in, sollicitudin varius quam. Proin dictum urna ac diam fermentum tempus. Pellentesque urna urna, ullamcorper a tincidunt dignissim, venenatis in nisi. Vivamus in volutpat tellus. Etiam fermentum luctus posuere.</p>
          <br>
          <p><a rel="nofollow" href="https://www.tooplate.com/view/2114-pixie">Pixie HTML Template</a> can be converted into your desired CMS theme. You can use this Bootstrap v4.1.3 layout for any online shop. Please tell your friends about <a rel="nofollow" href="https://www.facebook.com/tooplate/">Tooplate</a>. Thank you.</p>
          <div class="share">
            <h6>Find us on: <span><a href="#"><i style="background: #800080;" class="fa fa-facebook"></i></a><a href="#"><i style="background: #800080;" class="fa fa-linkedin"></i></a><a href="#"><i style="background: #800080;" class="fa fa-twitter"></i></a></span></h6>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- About Page Ends Here -->


 <!-- Contact Page Starts Here -->
 <div class="contact-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="section-heading">
          <div style="background: #800080;" class="line-dec"></div>
          <h1>Contact Us</h1>
        </div>
      </div>
      <div class="col-md-6">
        <div id="map">
            <!-- How to change your own map point
                       1. Go to Google Maps
                       2. Click on your location point
                       3. Click "Share" and choose "Embed map" tab
                       4. Copy only URL and paste it within the src="" field below
                -->

          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1197183.8373802372!2d-1.9415093691103689!3d6.781986417238027!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfdb96f349e85efd%3A0xb8d1e0b88af1f0f5!2sKumasi+Central+Market!5e0!3m2!1sen!2sth!4v1532967884907" width="100%" height="500px" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
      </div>
      <div class="col-md-6">
        <div class="right-content">
          <div class="container">
            <form id="contact" action="" method="post">
              <div class="row">
                <div class="col-md-6">
                  <fieldset>
                    <input name="name" type="text" class="form-control" id="name" placeholder="Your name..." required="">
                  </fieldset>
                </div>
                <div class="col-md-6">
                  <fieldset>
                    <input name="email" type="text" class="form-control" id="email" placeholder="Your email..." required="">
                  </fieldset>
                </div>
                <div class="col-md-12">
                  <fieldset>
                    <input name="subject" type="text" class="form-control" id="subject" placeholder="Subject..." required="">
                  </fieldset>
                </div>
                <div class="col-md-12">
                  <fieldset>
                    <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your message..." required=""></textarea>
                  </fieldset>
                </div>
                <div class="col-md-12">
                  <fieldset>
                    <button style="background-color: #800080" type="submit" id="form-submit" class="button">Send Message</button>
                  </fieldset>
                </div>
                <div class="col-md-12">
                  <div class="share">
                    <h6>You can also keep in touch on: <span><a href="#"><i style="background: #800080;" class="fa fa-facebook"></i></a><a href="#"><i style="background: #800080;" class="fa fa-linkedin"></i></a><a href="#"><i style="background: #800080;" class="fa fa-twitter"></i></a></span></h6>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Contact Page Ends Here -->

{% endblock content %}

   

templates/shoppapp/product_details.html
{% extends "base.html" %}
{% load static %}

{% block title %} Shopp Product Details {% endblock title %}

{% block content %}
    <!-- Page Content -->
    <!-- Single Starts Here -->
    <div class="single-product">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div style="background: #800080;" class="line-dec"></div>
              <h1>Product Details</h1>
            </div>
          </div>
          <div class="col-md-6">
              <img width="100%" height="100%" src="{{ product.product_image.url }}" />
          </div>
            <div class="col-md-6">
              <div class="right-content">
                <h4>{{ product.name }}</h4>
                <h6>NGN {{ product.discount_price }}</h6>
                <p>
                  {{ product.description }}
                </p>
                <span>{{ products.count }} left in stock</span>
                <form action="" method="get">
                  <label for="quantity">Quantity:</label>
                  <input name="quantity" type="quantity" class="quantity-text" id="quantity" 
                    onfocus="if(this.value == '1') { this.value = ''; }" 
                      onBlur="if(this.value == '') { this.value = '1';}"
                      value="1" />
                  <input style="background: #800080;" type="submit" class="button" value="Order Now!">
                </form>
                <div class="down-content">
                  <div class="categories">
                    <h6>Category: <span><a href="#">Women</a>,<a href="#">Fancy</a></span></h6>
                  </div>
                  <div class="share">
                    <h6>Share: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
    <!-- Single Page Ends Here -->


    <!-- Similar Starts Here -->
    <div class="featured-items">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div style="background: #800080;" class="line-dec"></div>
              <h1>You May Also Like</h1>
            </div>
          </div>
          <div class="col-md-12">
            <div class="owl-carousel owl-theme">
              {% for product in products  %}
              <a href="{% url 'shoppapp:product_details' product.id product.name %}">
                  <div class="featured-item">
                    <img src="{{ product.image.url }}" alt="Item 1">
                    <h4>{{ product.name }}</h4>
                    <div style="display: flex;">
                      <h6 style="text-decoration: line-through; color: red;">NGN {{product.price}}</h6> 
                      <h6 style="margin-left: 10px;">NGN {{product.price}}</h6>
                    </div>
                  </div>
                </a>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Similar Ends Here -->
    {% endblock content %}